In [1]:
#Write a function to compute 5/0 and use try/except to catch the exceptions. 
def divide():
    try:
        result = 5/0
    except ZeroDivisionError:
        print("division by zero")
        
divide()

division by zero


In [2]:
# Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
#Hint: Subject,Verb and Object should be declared in the program as shown below. 
#subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 


subjects=["Americans ","Indians"] 
verbs=["play","watch"]
objects=["Baseball","Cricket"] 
lst = [(s+" "+v+" "+o) for s in subjects for v in verbs for o in objects]
#print(lst) 
for i in lst:
    print(i)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [3]:
import numpy as np
x=np.array((1,2,3,4,5))
#print(x)
N = 5
#print(np.vander(x, N))
y=np.column_stack([x**(N-1-i) for i in range(N)])
print(y)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
